name: Package Maintainer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:    
  delete-package-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/delete-package-versions@v4
      if: github.event.repository.name == 'Slimefun-Secret'
      with: 
        package-name: 'com.github.slimefun.slimefun'
        package-type: 'maven'
        min-versions-to-keep: 5